import Head from "next/head";
import Link from "next/link";
import { demoResume } from "../lib/data";
import { TbSchool } from "react-icons/tb";
import { GrCertificate } from "react-icons/gr";
import { GiTargetPrize } from "react-icons/gi";
import { GrWorkshop } from "react-icons/gr";
import { MdOutlineSchool } from "react-icons/md";
import { useEffect, useState } from "react";
import React from "react";
import { useScroll } from "framer-motion";
import { motion, useViewportScroll, useTransform } from "framer-motion";
import { MdOutlineNavigateBefore } from "react-icons/md";
import { MdOutlineNavigateNext } from "react-icons/md";
import { MdOutlineVerified } from "react-icons/md";
import { useRef } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
export default function Home() {
  const data = demoResume();
  const [project, setProject] = useState("null");
  const [certificate, setCertificate] = useState("null");

  const [viewImage, setViewImage] = useState(false);
  const [count, setcount] = useState(0);

  useEffect(() => {
    AOS.init({
      // Global settings:
      disable: false, // accepts following values: 'phone', 'tablet', 'mobile', boolean, expression or function
      startEvent: "DOMContentLoaded", // name of the event dispatched on the document, that AOS should initialize on
      initClassName: "aos-init", // class applied after initialization
      animatedClassName: "aos-animate", // class applied on animation
      useClassNames: false, // if true, will add content of `data-aos` as classes on scroll
      disableMutationObserver: false, // disables automatic mutations' detections (advanced)
      debounceDelay: 50, // the delay on debounce used while resizing window (advanced)
      throttleDelay: 99, // the delay on throttle used while scrolling the page (advanced)

      // Settings that can be overridden on per-element basis, by `data-aos-*` attributes:
      offset: 120, // offset (in px) from the original trigger point
      delay: 0, // values from 0 to 3000, with step 50ms
      duration: 400, // values from 0 to 3000, with step 50ms
      easing: "ease", // default easing for AOS animations
      once: false, // whether animation should happen only once - while scrolling down
      mirror: false, // whether elements should animate out while scrolling past them
      anchorPlacement: "top-bottom", // defines which position of the element regarding to window should trigger the animation
    });
  }, []);
  const [photos, setPhotos] = useState([
    "https://cdna.artstation.com/p/assets/images/images/005/322/138/large/artem-netyagin-a9865717-f1d0-479a-b914-f9b5310a25e5-1.jpg?1490197682",
    "https://cdnb.artstation.com/p/assets/images/images/005/327/609/large/artem-netyagin-6.jpg?1490226607",
    "https://cdnb.artstation.com/p/assets/images/images/005/322/135/large/artem-netyagin-4d83187c-9b4d-425b-a348-1ab45fb0140d-3.jpg?1490197678",
    "https://cdnb.artstation.com/p/assets/images/images/005/322/139/large/artem-netyagin-d63ac63d-2a84-4200-810f-737e17e3b5ea-11.jpg?1490197687",
    "https://cdnb.artstation.com/p/assets/images/images/066/255/087/large/mu-yujiang-00002-sk.jpg?1692451999",
  ]);
  const { scrollYProgress } = useViewportScroll();
  const scale = useTransform(scrollYProgress, [0, 2], [0.1, 2]);
  <style jsx>{`
    .highlight {
      filter: none; // No blur
      border: 2px solid #cd9946; // Add a border to highlight
    }

    .blur {
      filter: blur(1px); // Apply a slight blur to non-highlighted images
      opacity: 0.7; // Reduce opacity for a faded look
    }
  `}</style>;
  const photo = [
    "https://cdna.artstation.com/p/assets/images/images/005/322/138/large/artem-netyagin-a9865717-f1d0-479a-b914-f9b5310a25e5-1.jpg?1490197682",
    "https://cdnb.artstation.com/p/assets/images/images/005/327/609/large/artem-netyagin-6.jpg?1490226607",
    "https://cdnb.artstation.com/p/assets/images/images/005/322/135/large/artem-netyagin-4d83187c-9b4d-425b-a348-1ab45fb0140d-3.jpg?1490197678",
    "https://cdnb.artstation.com/p/assets/images/images/005/322/139/large/artem-netyagin-d63ac63d-2a84-4200-810f-737e17e3b5ea-11.jpg?1490197687",
    "https://cdnb.artstation.com/p/assets/images/images/066/255/087/large/mu-yujiang-00002-sk.jpg?1692451999",
  ];

  const [currentImageIndex, setCurrentImageIndex] = useState(0);

  // Function to show the next image
  const showNextImage = () => {
    setCurrentImageIndex((prevIndex) => (prevIndex + 1) % photo.length);
  };

  // Function to show the previous image
  const showPreviousImage = () => {
    setCurrentImageIndex((prevIndex) =>
      prevIndex === 0 ? photo.length - 1 : prevIndex - 1
    );
  };

  return (
    <div>
      <Head>
        <title>RESUME TEMPLETES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative  h-screen">
        <div
          className="h-full w-full bg-cover bg-center  fixed"
          style={{
            backgroundImage: `url("https://bootstrapmade.com/demo/templates/Folio/assets/img/home-bg.jpg")`,
            backgroundSize: "cover", // Default background size
          }}
        ></div>
        <div className="absolute w-full  md:top-[40%] top-[60%] sm:bg-center text-white ">
          <div>
            <motion.h1
              initial={{ opacity: 0, x: 30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.5, duration: 1.5 }}
              className="text-5xl uppercase font-bold pl-[10%]  text-white"
            >
              {data.personal.firstName} {data.personal.lastName}
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, x: 30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.5, duration: 1.5 }}
              className="text-base font-semibold pl-[10%]  text-white tracking-widest py-5"
            >
              {data.personal.role}
            </motion.p>
          </div>
        </div>
      </div>
      <div className="bg-gray-100 min-w-fit absolute lg:w-[100%]">
        <div className="lg:flex p-10 md:pt-20  ">
          <div className="md:w-[50%]">
            <div className="">
              <img
                className="  bg-[#b8a99f] md: p-4 sm:mx-fit mx-auto"
                src="https://bootstrapmade.com/demo/templates/Folio/assets/img/me.jpg"
              />
            </div>
          </div>
          <div className=" w-full md:w-1/2  lg:w-1/2 py-4 mt-8  lg:mt-5 lg:px-10 ">
            <p
              className="font-serif text-[28px] text-[#b39463] "
              data-aos="fade-up"
              data-aos-offset="200"
              // data-aos-delay=""
              data-aos-duration="5  00"
              // data-aos-easing="ease-in-out"
              // data-aos-mirror="true"
              // data-aos-once="false"
            >
              im a ux /ui designer austin based who loves clean, simple & unique
              design. i also enjoy crafting brand identities, icons, &
              ilustration work.
            </p>
            <p className="text-[18px] pt-7 pr-14 text-[#cd9946] font-thin">
              To an English person, it will seem like simplified English, as a
              skeptical Cambridge friend of mine told me what Occidental is. The
              European languages are members of the same family.English person.
            </p>
          </div>
        </div>

        {/* Icons  */}
        <div className="flex-nowrap py-10 flex justify-center  md:gap-4 ">
          <div className="px-10 py-3 hover:scale-105">
            <div className="scale-125">
              {" "}
              <TbSchool className="text-3xl md:text-5xl text-[#cd9946]" />
            </div>
          </div>
          <div className="px-10 py-3 hover:scale-105">
            <div>
              {" "}
              <GrCertificate className="text-3xl md:text-5xl text-[#cd9946]" />
            </div>
          </div>
          <div className="px-10 py-3 hover:scale-105">
            <div>
              {" "}
              <GrWorkshop className="text-3xl md:text-5xl text-[#cd9946]" />
            </div>
          </div>
          <div className="px-10 py-3 hover:scale-105">
            <div>
              {" "}
              <GiTargetPrize className="text-3xl md:text-5xl text-[#cd9946] " />
            </div>
          </div>
        </div>
        {/* projects  */}

        <div className="w-[100%]  min-w-fit  overflow-hidden bg-white h-fit md:h-screen ">
          <p className="font-serif uppercase mt-12 font-bold tracking-wide text-lg md:text-3xl text-center">
            Projects
          </p>
          <div className=" flex justify-evenly mt-5">
            {data.projects.map((project) => (
              <div className="">
                <p
                  className="hover:scale-105 hover:font-semibold cursor-pointer py-5 text-[#cd9946]"
                  onClick={() => {
                    setProject(project.name);
                  }}
                >
                  {project.name}
                  {/* <img src="https://cdnb.artstation.com/p/assets/images/images/005/322/135/large/artem-netyagin-4d83187c-9b4d-425b-a348-1ab45fb0140d-3.jpg?1490197678"/> */}
                </p>
              </div>
            ))}
          </div>

          <div className="flex justify-center md:mt-10 my-5">
            <div className="hidden md:flex w-[90%] space-x-0 items-center justify-center">
              {photos.map((photo, index) => (
                <div
                  key={index}
                  className={`relative w-[300px] h-[300px] transition-transform duration-500 transform ${
                    index === 2 ? "focus" : "blur"
                  }`}
                  style={{
                    paddingTop: index == 0 ? "" : "10",
                    marginLeft: index === 2 ? "-10px" : "0", // Adjust margin for the first image
                    zIndex: index === 2 ? 2 : index === 1 ? 1 : 0, // Bring image 2 to the front and image 1 behind it
                    backgroundImage: `url(${photo})`,
                    backgroundSize: "cover",
                    backgroundPosition: "center",
                    borderRadius: "15px", // All images have the same border radius
                    filter: index === 2 ? "none" : "blur(1px)", // Apply blur to images except the focused one
                    boxShadow:
                      index === 2 ? "0px 0px 10px rgba(0, 0, 0, 0.8)" : "none",
                    border: index === 2 ? "2px solid #ffffff" : "none",
                    transform: index === 2 ? "scale(1.2)  " : "scale(1)", // Scale the focused image
                    transition:
                      "transform 0.5s ease-in-out, filter 0.5s ease-in-out, box-shadow 0.5s ease-in-out, z-index 0.5s ease-in-out, border 0.5s ease-in-out, margin-left 0.5s ease-in-out", // Include margin-left in the transition
                  }}
                >
                  {/* Image content */}
                </div>
              ))}
            </div>

            <div className="md:hidden flex flex-wrap justify-center ">
              <button
                onClick={showPreviousImage}
                className="ml-2 text-2xl  py-1 pr-2 text-white "
              >
                <MdOutlineNavigateBefore />
              </button>
              <img
                src={photo[currentImageIndex]}
                alt={`Image ${currentImageIndex + 1}`}
                className="max-h-[400px] max-w-[300px]"
              />

              <button
                onClick={showNextImage}
                className="ml-2 text-2xl py-1 text-white "
              >
                <MdOutlineNavigateNext />
              </button>
            </div>
          </div>
          <div className="mx-10">
            {viewImage && (
              <div className="fixed top-0 left-0 w-full  h-[75%] delay-300 flex items-center justify-center z-50">
                <div className="fixed inset-0 bg-black "></div>
                <div className="bg-white z-50 p-4 rounded-md">
                  <img
                    src="https://cdnb.artstation.com/p/assets/images/images/005/322/135/large/artem-netyagin-4d83187c-9b4d-425b-a348-1ab45fb0140d-3.jpg?1490197678"
                    alt="Image"
                  />
                  <button
                    onClick={() => {
                      setViewImage(false);
                    }}
                    className="mt-2 bg-red-500 text-white px-4 py-2 rounded-md"
                  >
                    Close
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
        {/* Certification  */}
        <div>
          <div className="hidden md:block" style={{ overflowX: "hidden" }}>
            <motion.div
              style={{
                scale,
                // overflowX: "hidden",
                whiteSpace: "nowrap",
                width: "100%",
              }}
              className="wrapper overflow-hidden w-full bg-gray-100 h-auto md:h-auto"
            >
              <p className="text-center  font-mono font-semibold tracking-wide text-[32px] pt-[6%]">
                {" "}
                CERTIFICATION
              </p>
              <div className=" flex item flex-nowrap justify-around mt-5">
                {data.certifications.map((Certificate) => (
                  <div className="mx-auto ">
                    <p
                      className="cursor-pointer py-1 text-[#cd9946]"
                      onClick={() => {
                        setCertificate(Certificate.name);
                      }}
                    >
                      <img
                        className="h-[70mm]  w-[100mm]   "
                        src="https://support.edx.org/hc/article_attachments/1500017389801/Screen_Shot_2021-05-13_at_11.00.15_AM.png"
                      />
                      <p className="py-5">{Certificate.title}</p>
                    </p>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
          <div className="md:hidden pt-5" style={{ overflowX: "hidden" }}>
            <div className="wrapper overflow-hidden w-full bg-gray-100 h-auto md:h-auto">
              <p className="text-center font-mono font-semibold tracking-wide text-[32px] ">
                {" "}
                CERTIFICATION
              </p>
              <div className=" flex item flex-wrap  mt-5">
                {data.certifications.map((Certificate) => (
                  <div className="mx-auto py-3 ">
                    <p
                      className="cursor-pointer  text-[#cd9946]"
                      onClick={() => {
                        setCertificate(Certificate.name);
                      }}
                    >
                      <img
                        className="h-[70mm]  w-[100mm]   "
                        src="https://support.edx.org/hc/article_attachments/1500017389801/Screen_Shot_2021-05-13_at_11.00.15_AM.png"
                      />
                      <p className="text-center py-1">{Certificate.title}</p>
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
        {/* RESUME */}
        <div className="align-middle ">
          <div className=" bg-opacity-95 bg-[conic-gradient(at_top,_var(--tw-gradient-stops))] from-orange-900 via-amber-100 to-orange-900 bg-cover bg-center bg-no-repeat ">
            <div className=" bg-opacity-95 rounded-full  bg-no-repeat ">
              <img
                className="p-3 mx-auto shadow-2xl border-4 border-white h-screen"
                src="https://gdoc.io/uploads/University-Student-Resume-Template-web1.jpg"
                alt="Responsive Image"
              />
            </div>
          </div>
        </div>
        {/* SKILLS */}
        <div className="flex mx-auto my-7">
          {/* technical skills */}
          <div
            className="flex flex-col w-[50%] "
            style={{ overflowX: "hidden" }}
          >
            <p className="font-serif uppercase mt-5 font-bold tracking-wide text-lg md:text-3xl text-center">
              Technical Skills
            </p>
            <hr className="h-[0.41mm] mx-10 my-3 bg-[#cd9946]" />
            <div className="mx-auto md:grid md:grid-cols-2 gap-4 my-2">
              {data.technicalSkills.map((tskills) => (
                <p className="text-center rounded-md font-semibold  bg-white  my-4 md:p-5 p-3  shadow-xl  hover:cursor-pointer text-lg md:text-xl">
                  {tskills.name}
                </p>
              ))}
            </div>
          </div>
          {/* soft skills */}
          <div className="flex flex-col w-[50%]">
            <p className="font-serif uppercase mt-5 font-bold tracking-wide text-lg md:text-3xl text-center">
              Soft Skills
            </p>
            <hr className="h-[0.41mm] mx-10 my-3 bg-[#cd9946]" />
            <div className="mx-auto md:grid md:grid-cols-2 gap-4 my-2">
              {data.softSkills.map((skills) => (
                <p className="text-center rounded-md font-semibold  bg-white  my-4 md:p-5 p-3  shadow-xl  hover:cursor-pointer text-lg md:text-xl">
                  {skills.name}
                </p>
              ))}
            </div>
          </div>
        </div>
        {/* EDUCATION */}
        <div className=" mx-auto pb-10 bg-white pt-[2%]">
          <p className="font-serif uppercase mt-5 font-bold tracking-wide pb-[4%] text-xl md:text-3xl text-center">
            EDUCATION
          </p>
          <div className="md:grid md:grid-cols-4 gap-4 ">
            {data.education.map((e) => (
              <div className="mx-auto p-5 text-center rounded-md md:bg-[#e5d5bc] md:shadow-2xl">
                <MdOutlineSchool className="text-[55px] m-1 fill-black mx-auto " />
                <p className="text-xl font-bold  text-gray-800 py-2">
                  {e.institution}
                </p>
                <p className="py-1 text-lg  ">
                  [{e.startDate}] -[{e.endDate}]
                </p>
                <p className="py-1 text-lg  ">{e.fieldOfStudy}</p>
                <p className="py-1 text-lg  ">{e.typeOfDegree}</p>
                <p className="py-1 text-lg  ">CGPA - {e.gpa}</p>
              </div>
            ))}
          </div>
        </div>
        {/* work */}
        <div className="mx-auto bg-cover bg-center bg-[#F5F3F0] pb-10">
          <div className="pt-[2%]  mx-auto ">
            <p className="font-serif uppercase mt-5 font-bold tracking-wide pb-[4%] text-xl md:text-3xl text-center">
              Professional Experience
            </p>
            <div className="md:flex">
              <div className="md:px-[40px]">
                {data.work.map((w, index) => (
                  <div
                    className="mx-auto p-5 text-left  rounded-md "
                    key={index}
                  >
                    <p className="text-xl md:text-2xl tracking-wide font-bold text-gray-800 py-2">
                      {w.company}
                    </p>
                    <p className="py-1 md:text-lg">
                      [{w.from}] -[{w.to}]
                    </p>
                    <p className="py-1 md:text-lg">{w.designation}</p>
                    <p className="py-1 hover:cursor-pointer underline text-blue-900 md:text-lg">
                      {w.website}
                    </p>
                    <p className="py-1 md:text-lg">{w.summary.data}</p>
                  </div>
                ))}
              </div>
              <div className="md:block hidden">
                <img src="https://www.clockwork.com/wp-content/uploads/2022/07/human-centered-experience-design-1024x1021-1.png" />
              </div>
            </div>
          </div>
        </div>
        {/* ACHIVMNTS */}
        <div className="mx-auto pb-10 pt-[3%]">
          <p className="font-serif uppercase mt-5 font-bold tracking-wide text-lg md:text-3xl text-center">
            achievements
          </p>
          <div className="mt-[5%] mx-auto">
            {data.achievements.map((achievements) => (
              <div className="flex justify-evenly pb-5 md:pb-10">
                <div className="">
                  <MdOutlineVerified className=" md:my-6 my-1 fill-yellow-700 text-[40px] p-1 sm:mx-5 mx-1 md:text-[100px] " />
                </div>
                <div className="">
                  <p className="text-lg md:text-xl tracking-wide font-bold text-gray-800 py-2">
                    {achievements.title}
                  </p>
                  <p className="py-1 md:text-lg">
                    Date : [{achievements.date}]
                  </p>
                  <p className="py-1 md:text-lg">{achievements.issuer}</p>
                  <p className="py-1 md:text-lg">{achievements.summary.data}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
        {/* footer */}
        <div className="bg-white">
          <div className="max-w-screen-xl px-4 py-12 mx-auto space-y-8 overflow-hidden sm:px-6 lg:px-8">
            <nav className="flex flex-wrap justify-center -mx-5 -my-2">
              <div className="px-5 py-2">
                <a
                  href="#"
                  className="text-base leading-6 text-gray-500 hover:text-gray-900"
                >
                  About
                </a>
              </div>
              <div className="px-5 py-2">
                <a
                  href="#"
                  className="text-base leading-6 text-gray-500 hover:text-gray-900"
                >
                  Blog
                </a>
              </div>
              <div className="px-5 py-2">
                <a
                  href="#"
                  className="text-base leading-6 text-gray-500 hover:text-gray-900"
                >
                  Team
                </a>
              </div>
              <div className="px-5 py-2">
                <a
                  href="#"
                  className="text-base leading-6 text-gray-500 hover:text-gray-900"
                >
                  Pricing
                </a>
              </div>
              <div className="px-5 py-2">
                <a
                  href="#"
                  className="text-base leading-6 text-gray-500 hover:text-gray-900"
                >
                  Contact
                </a>
              </div>
              <div className="px-5 py-2">
                <a
                  href="#"
                  className="text-base leading-6 text-gray-500 hover:text-gray-900"
                >
                  Terms
                </a>
              </div>
            </nav>
            <div className="flex justify-center mt-8 space-x-6">
              <a href="#" className="text-gray-400 hover:text-gray-500">
                <span className="sr-only">Facebook</span>
                <svg
                  className="w-6 h-6"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    fill-rule="evenodd"
                    d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </a>
              <a href="#" className="text-gray-400 hover:text-gray-500">
                <span className="sr-only">Instagram</span>
                <svg
                  className="w-6 h-6"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    fill-rule="evenodd"
                    d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </a>
              <a href="#" className="text-gray-400 hover:text-gray-500">
                <span className="sr-only">Twitter</span>
                <svg
                  className="w-6 h-6"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"></path>
                </svg>
              </a>
              <a href="#" className="text-gray-400 hover:text-gray-500">
                <span className="sr-only">GitHub</span>
                <svg
                  className="w-6 h-6"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    fill-rule="evenodd"
                    d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </a>
              <a href="#" className="text-gray-400 hover:text-gray-500">
                <span className="sr-only">Dribbble</span>
                <svg
                  className="w-6 h-6"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    fill-rule="evenodd"
                    d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </a>
            </div>
            <p className="mt-8 text-base leading-6 text-center text-gray-400">
              © 2021 SomeCompany, Inc. All rights reserved.
            </p>
          </div>
        </div>
      </div>

      <style jsx>{`
        .highlight {
          filter: none; // No blur
          border: 2px solid #cd9946; // Add a border to highlight
        }

        .blur {
          filter: blur(0.5px); // Reduce the blur effect
          opacity: 0.7; // Reduce opacity for a faded look
        }
      `}</style>
    </div>
  );
}
